### PR TITLE
KumoWorks

### PR DESCRIPTION
**Pull request by shun-iwasawa**
Added KumoWorks download button and page.
Please note that the Spanish page is not prepared.

### CODE REVIEW

**Comment by masafumi-inoue** [comment]
LGTM

**Comment by gab3d** [comment]
@shun-iwasawa 
How can I be of help, regarding the Spanish page?

**Comment by shun-iwasawa** [comment]
Wow, thank you @gab3d for your kind proposal!

The Spanish page needed to be translated is [here](https://github.com/opentoonz/opentoonz.github.io/blob/master/es/download/kumoworks.html).
As you can see, it consists of two contents - `What is KumoWorks?` and `KumoWorks Terms of Use` .
The terms of use are based on OpenToonz's ones (so I think you can work based on Spanish version of them), but revised in several parts as follows:

- Added a term that users under 19 years old shall be with prior consent of their parents. ([In premises](https://github.com/opentoonz/opentoonz.github.io/blob/master/es/download/kumoworks.html#L64)) 
- Added a rule in case of suspension or termination of the service. ([In article 6.2](https://github.com/opentoonz/opentoonz.github.io/blob/master/es/download/kumoworks.html#L105))
- Clarified rules when we will revise the terms. ([In article 8](https://github.com/opentoonz/opentoonz.github.io/blob/master/es/download/kumoworks.html#L110-L111))
- Added conditions for assignment of the status. ([In article 9](https://github.com/opentoonz/opentoonz.github.io/blob/master/es/download/kumoworks.html#L113-L115))

Some changes were made reflecting the coming amendment to the Japanese Civil Code next year.
The same revision will be applied to both OpenToonz and GTS' terms of use soon.

You can post the translation PR to this repository or just upload the translated text here so that I can replace the HTML on behalf of you.

**Comment by gab3d** [comment]
@shun-iwasawa 
Here I attach the Spanish version of KumoWorks *download* page (with new Terms), as well as minor updates to the Spanish versions of OpenToonz *index* and *download* pages (kept OT Terms as they currently are).

(Edit: I've realized afterwards that I haven't included the first item you pointed out in the list, so now I've reuploaded the file.)
[web_es_001.zip](https://github.com/opentoonz/opentoonz.github.io/files/3100782/web_es_001.zip)

**Comment by gab3d** [comment]
@shun-iwasawa
Please don't forget about this one. ;)

**Comment by shun-iwasawa** [comment]
@gab3d Thanks for the Spanish translation and the heads-up! I'll work on it right away.

**Comment by shun-iwasawa** [comment]
Done :-)

**Comment by gab3d** [comment]
@shun-iwasawa 
I've just checked the website and saw you didn't include the updated *index.html* file, was it because of something wrong in it? If so, please tell me what it is so I can fix it. :+1:

**Comment by shun-iwasawa** [comment]
@gab3d 
[Here](https://github.com/opentoonz/opentoonz.github.io/pull/46/files#diff-ae205a365903865d8948f2b38adf4333) are changes what I applied to `index.html` in the last PR. Please let me know if they are correct...

If they are fine but the website still displays the old content on your end, cached data of the old version of the page may be shown in your browser. Please try removing them. Thanks!

**Comment by gab3d** [comment]
@shun-iwasawa 
Sorry, but I've checked in several PCs and I still see the older version of the Spanish index page.
The changes, as seen in the link in you previous message, are correct though. 🤔

**Comment by shun-iwasawa** [comment]
Ah! I think I understand the situation.
You modified mainly the section titles. However the appearance did not changed in the page since they are actually displayed with images! 
I think I can fix it by reflecting your changes to the title images. Sorry for the confusion. Thanks!

**Comment by gab3d** [comment]
That must be it! I wasn't really aware of that...
Thank you!

**Comment by shun-iwasawa** [comment]
It's done!

**Comment by gab3d** [comment]
どうもありがとう

**Pull request merged**
