### PR TITLE
link to nightly builds

### LINKED ISSUE #57: Add Nightly Releases link to Downloads page
Because Opentoonz official releases are expected to be annual users often are unaware of interim releases that may address their needs, fix bugs and introduce new features.

Adding a link to Nightly Releaese on the downloads page will help highlight that Opentoonz is continuously improved and point users to where they can test the latest releases.

What the link might look like on the current page:

Add Nightly releases link to Download page

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR resolves #57 .  
Added download buttons for nightly build versions.

@gab3d @pikhosh 
It would be appreciated if you could translate the texts. Thanks!

### CODE REVIEW

**Comment by pikhosh** [comment]
I do not know why, but I can not push commit to this PR! Should I create a new PR?

**Comment by shun-iwasawa** [comment]
@pikhosh 
Because this PR is mine (i.e. requesting merging some branch in MY remote repository to the master branch) and is not yet merged. I'll merge this so that you can post a separate PR of your translation based on the latest master including this PR. Thanks!

**Comment by DarrenTAnims** [comment]
This is great to see @shun-iwasawa. Thank you for adding this. Hopefully more new users will try this out.
One addition: It would be good to have a link listing features & bugs that are included in this latest nightly, added since the last full release, so that each user can judge whether it's worth their time upgrading and also to promote the new features, so they will be tried out by users discovering them. This would be good for each feature/bug to link to the original github post, so the full detail of the feature/bug can be evaluated.

**Comment by gab3d** [comment]
@DarrenTAnims while I obviously see the idea to be helpful, (and while Rodney will say for sure what he thinks of it) I foresee that this would take a good deal of extra "paperwork" to keep updated.

**Comment by shun-iwasawa** [comment]
@DarrenTAnims
How about adding a link to one of the following?:
- https://github.com/opentoonz/opentoonz/commits/nightly    (Commit history of the nightly build)
- https://github.com/opentoonz/opentoonz/compare/v1.5.0...nightly    (Comparing changes between v1.5.0 and the nightly build)

**Comment by DarrenTAnims** [comment]
It could @gab3d, but the issued being fixed are automatically logged in GIT as the work is done.

**Comment by DarrenTAnims** [comment]
Thanks @shun-iwasawa.

I was originally thinking of linking to the nightly builds page (https://github.com/opentoonz/opentoonz_nightlies/releases), but these 2 are good options too. I don't want to introduce more work for you, so a page that is updated by the code submission system is going to be better.
I think the commits page (https://github.com/opentoonz/opentoonz/commits/nightly) would be better, because for some, just reading the titles of the fixes and dates of them would be enough to persuade you to update. And for others wanting more details, then they can click on the #Number links, to read the full details, with examples/screenshots.

**Pull request merged**
