### PR TITLE
Persian language for OpenToonz website by pikhosh

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is based on #64 by @pikhosh with the changes as follows:

- Modified to right to left layout
- Added Persian button on Spanish page

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
@pikhosh can you please check if the right to left layout works properly?
You can preview the page [here](https://htmlpreview.github.io/?https://github.com/shun-iwasawa/opentoonz.github.io/blob/piki-shabpareh-Persian/fa/index.html).

Also please let me know if you would like to complete the remaining translations before releasing the Persian pages.

**Comment by pikhosh** [comment]
> @pikhosh can you please check if the right to left layout works properly?
> You can preview the page [here](https://htmlpreview.github.io/?https://github.com/shun-iwasawa/opentoonz.github.io/blob/piki-shabpareh-Persian/fa/index.html).
> 
> Also please let me know if you would like to complete the remaining translations before releasing the Persian pages.

Hello! Yes; The theme is RTL properly and I really thank you for that 😊

And I will definitely try to do the remaining translations in the next few days (maybe two weeks).

**Comment by pikhosh** [comment]
@shun-iwasawa Hello again! excuse me; I wanted to ask how should I add new translations on modified files for right to left?
I'm searching but I have no idea how to do it. 😶

**Comment by pikhosh** [comment]
@shun-iwasawa Hello again! I wanted to ask how should I put new Persian translations on the modified files for right to left?
I tried, but I can not make a new Commit on this PR. 🙄

**Comment by shun-iwasawa** [comment]
There are two ways that you can use to add new translation as follows:

1. Adding translation to your original PR ( #64 )

    - Move to your original branch. 
      `> git checkout Persian`
    - Complete the translation.
    - Adding a new commit for it.
      `> git commit -a -m "complete Persian translation"`
    - Push it to the remote repo.
      `> git push origin Persian`

    The changes will automatically update the PR #64 so that I can manually update this PR.

1. Adding translation based on this PR
     
    - Create the working branch.
      `> git checkout -b shun-iwasawa-piki-shabpareh-Persian master`
    - Pull this branch to your local repo.
       `> git pull https://github.com/shun-iwasawa/opentoonz.github.io.git piki-shabpareh-Persian`
    - Complete the translation.
    - Adding a new commit for it.
      `> git commit -a -m "complete Persian translation"`
    - Push it to the remote repo.
      `> git push origin shun-iwasawa-piki-shabpareh-Persian`
    - Create a new PR for it.

    Once your PR is merged, this PR and the original PR #64 will be stated as "merged" accordingly.

**Comment by pikhosh** [comment]
> There are two ways that you can use to add new translation as follows:
> 
> 1. Adding translation to your original PR ( #64 )
>    
>    * Move to your original branch.
>      `> git checkout Persian`
>    * Complete the translation.
>    * Adding a new commit for it.
>      `> git commit -a -m "complete Persian translation"`
>    * Push it to the remote repo.
>      `> git push origin Persian`
>    
>    The changes will automatically update the PR #64 so that I can manually update this PR.
> 2. Adding translation based on this PR
>    
>    * Create the working branch.
>      `> git checkout -b shun-iwasawa-piki-shabpareh-Persian master`
>    * Pull this branch to your local repo.
>      `> git pull https://github.com/shun-iwasawa/opentoonz.github.io.git piki-shabpareh-Persian`
>    * Complete the translation.
>    * Adding a new commit for it.
>      `> git commit -a -m "complete Persian translation"`
>    * Push it to the remote repo.
>      `> git push origin shun-iwasawa-piki-shabpareh-Persian`
>    * Create a new PR for it.
>    
>    Once your PR is merged, this PR and the original PR #64 will be stated as "merged" accordingly.

excuse me; I have done 3 commit for this PR (and based on your corrections) via GitHub desktop; But I can not Push them (gives me an error).

Will my changes disappear now with the methods you mentioned or not?

(Again, I apologize for the many questions.)

**Comment by pikhosh** [comment]
@shun-iwasawa It seems that I was finally able to do something! 😅

Apparently, I was able to combine this PR and my 3 new commit with "Persian" branch! 🤔

And I now feel that everything in #64 is right and proper. 🤨

**Pull request merged**
